services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    ports:
      - "8000:8000"
    volumes:
      - project-management-data:/data

volumes:
  project-management-data:
